from sqlalchemy import (
    Column,
    Float,
    Float,
    String,
    Integer,
    BigInteger,
    Boolean,
    DateTime,
    Text,
)
from sqlalchemy.ext.declarative import declarative_base
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo
from sqlalchemy import ForeignKey


class Base(declarative_base()):
    __abstract__ = True

    def to_dict(self):
        return {
            column.name: getattr(self, column.name) for column in self.__table__.columns
        }


class User(Base):
    __tablename__ = "users"
    first_name = Column(String(50), nullable=False)
    last_name = Column(String(50), nullable=False)
    user_name = Column(String(50), nullable=False)
    upn = Column(String(100), primary_key=True, nullable=False)
    email = Column(String(100))
    phone = Column(String(20))
    role = Column(String(50), nullable=False)
    reporting_manager = Column(String(100))
    preferred_notification_type = Column(String(50))
    country = Column(String(50))
    responsible_country = Column(String(50))
    is_active = Column(Boolean)
    sales_organization = Column(String(500))
    sales_office = Column(String(50))
    sales_group = Column(String(50))
    sales_territory = Column(String(500))
    teleselling_territory = Column(String(50))
    bd_territory_name = Column(String(50))
    ca_territory_name = Column(String(50))
    mc_territory_name = Column(String(50))
    p1_territory_name = Column(String(50))
    p2_territory_name = Column(String(50))
    p3_territory_name = Column(String(50))
    p4_territory_name = Column(String(50))
    p5_territory_name = Column(String(50))
    ncb_territory_name = Column(String(50))
    last_login_on = Column(DateTime(timezone=True))
    client = Column(String(50))
    created_on = Column(DateTime(timezone=True))
    created_by = Column(String(50))
    modified_on = Column(DateTime(timezone=True))
    modified_by = Column(String(50))
    reward_point = Column(Integer)


class Outlet(Base):
    __tablename__ = "outlets"

    name = Column(String(100))
    code = Column(String(50), primary_key=True)
    outlet_type = Column(String(50))
    is_key_outlet = Column(Boolean)
    is_smart = Column(Boolean)
    country = Column(String(50))
    state = Column(String(50))
    city = Column(String(50))
    street = Column(String(100))
    address_2 = Column(String(100))
    address_3 = Column(String(100))
    address_4 = Column(String(100))
    postal_code = Column(String(20))
    retailer = Column(String(100))
    primary_phone = Column(String(20))
    primary_sales_rep = Column(String(50))
    sales_rep_name = Column(String(100))
    technician = Column(String(100))
    market = Column(String(50))
    sales_target = Column(Integer)
    client = Column(String(50))
    latitude = Column(String(50))
    longitude = Column(String(50))
    trade_channel = Column(String(50))
    trade_group = Column(String(50))
    trade_group_code = Column(String(50))
    is_active = Column(Boolean)
    customer_tier = Column(String(50))
    sub_trade_channel = Column(String(50))
    sales_organization = Column(String(50))
    sales_office = Column(String(50))
    sales_group = Column(String(50))
    sales_territory = Column(String(50))
    teleselling_territory_name = Column(String(50))
    business_developer_territory_name = Column(String(50))
    credit_approver_territory_name = Column(String(50))
    merchandizer_territory_name = Column(String(50))
    p1_territory_name = Column(String(50))
    p2_territory_name = Column(String(50))
    p3_territory_name = Column(String(50))
    p4_territory_name = Column(String(50))
    p5_territory_name = Column(String(50))
    reserve_route_name = Column(String(50))
    rd_customer_name = Column(String(100))
    time_zone = Column(String(150))
    sub_client = Column(String(50))
    cluster = Column(String(50))
    market_segment = Column(String(50))
    segment = Column(String(50))
    environment = Column(String(50))
    assortment_1 = Column(String(50))
    assortment_2 = Column(String(50))
    assortment_3 = Column(String(50))
    assortment_4 = Column(String(50))
    assortment_5 = Column(String(50))
    barcode = Column(String(50))
    local_cluster = Column(String(50))
    local_trade_channel = Column(String(50))
    chain = Column(String(50))
    region_name = Column(String(50))
    mobile_phone = Column(String(20))
    email = Column(String(100))
    cpl_name = Column(String(50))
    extra_field = Column(String(100))
    created_on = Column(DateTime(timezone=True))
    created_by = Column(String(50))
    modified_on = Column(DateTime(timezone=True))
    modified_by = Column(String(50))
    bdaa = Column(String(50))
    cmmind = Column(String(50))
    combined_asset_capacity = Column(Integer)
    asm_name = Column(String(50))
    asm_email = Column(String(100))
    tsm_name = Column(String(50))
    tsm_email = Column(String(100))


class Asset(Base):
    __tablename__ = "assets"

    asset_type = Column(String(50))
    bottler_equipment_number = Column(String(50))
    technical_id = Column(String(50))
    oem_serial_number = Column(String(50), primary_key=True)
    asset_ping = Column(DateTime(timezone=True))
    category = Column(String(50))
    is_competition = Column(Boolean)
    is_factory_asset = Column(Boolean)
    associated_in_factory = Column(Boolean)
    outlet = Column(String(100))
    outlet_code = Column(String(50))
    outlet_type = Column(String(50))
    store_location = Column(String(100))
    trade_channel = Column(String(50))
    customer_tier = Column(String(50))
    sub_trade_channel = Column(String(50))
    sales_organization = Column(String(50))
    sales_office = Column(String(50))
    sales_group = Column(String(50))
    sales_territory = Column(String(50))
    issue = Column(String(100))
    smart_device = Column(String(50))
    smart_device_type = Column(String(50))
    smart_device_ping = Column(String(50))
    gateway = Column(String(50))
    gateway_type = Column(String(50))
    gateway_ping = Column(String(50))
    last_scan = Column(DateTime)
    visit_scan_status = Column(String(50))
    client = Column(String(50))
    city = Column(String(50))
    street = Column(String(100))
    street_2 = Column(String(100))
    street_3 = Column(String(100))
    state = Column(String(50))
    country = Column(String(50))
    prime_position = Column(Boolean)
    is_missing = Column(Boolean)
    is_vision = Column(Boolean)
    is_smart = Column(Boolean)
    is_authorized_movement = Column(Boolean)
    is_unhealthy = Column(Boolean)
    latitude = Column(String(50))
    longitude = Column(String(50))
    last_known_latitude = Column(String(50))
    last_known_longitude = Column(String(50))
    geolocation_source = Column(String(50))
    location_accuracy = Column(Integer)
    displacement_meter = Column(Integer)
    is_power_on = Column(Boolean)
    latest_health_record_event_time = Column(DateTime(timezone=True))
    battery_level = Column(Integer)
    battery_status = Column(String(50))
    planogram = Column(String(50))
    responsible_bd_username = Column(String(50))
    responsible_bd_first_name = Column(String(50))
    responsible_bd_phone_number = Column(String(20))
    iot_solution = Column(String(50))
    has_sim = Column(Boolean)
    asset_associated_on = Column(DateTime(timezone=True))
    gateway_associated_on = Column(DateTime(timezone=True))
    acquisition_date = Column(DateTime(timezone=True))
    associated_by_bd_user_name = Column(String(50))
    associated_by_bd_name = Column(String(50))
    gateway_associated_by_bd_user_name = Column(String(50))
    gateway_associated_by_bd_name = Column(String(50))
    time_zone = Column(String(150))
    created_on = Column(DateTime(timezone=True))
    created_by = Column(String(50))
    modified_on = Column(DateTime(timezone=True))
    modified_by = Column(String(50))
    capacity_type = Column(String(50))
    sub_client = Column(String(50))
    latest_movement_record_event_time = Column(DateTime(timezone=True))
    latest_power_record_event_time = Column(DateTime(timezone=True))
    location_status = Column(String(50))
    last_location_status_on = Column(DateTime(timezone=True))
    latest_location_status_on = Column(DateTime(timezone=True))
    static_latitude = Column(String(50))
    static_longitude = Column(String(50))
    static_movement_status = Column(String(50))


class SmartDevice(Base):
    __tablename__ = "smart_devices"

    device_type = Column(String(50))
    manufacturer = Column(String(50))
    mac_address = Column(String(50), primary_key=True)
    serial_number = Column(String(50))
    order_serial_number = Column(String(50))
    shipped_country = Column(String(50))
    door_no = Column(Integer)
    bottler_equipment_number = Column(String(50))
    technical_identification_number = Column(String(50))
    gateway = Column(String(50))
    manufacturer_serial_number = Column(String(50))
    imei = Column(String(50))
    sim_number = Column(String(50))
    sim_provider = Column(String(50))
    plugin_connected_ffxy = Column(Boolean)
    last_ping = Column(DateTime(timezone=True))
    firmware_version = Column(String(50))
    ibeacon_uuid = Column(String(50))
    ibeacon_major = Column(Integer)
    ibeacon_minor = Column(Integer)
    eddystone_uid_namespace = Column(String(50))
    eddystone_uid_instance = Column(String(50))
    inventory_location = Column(String(50))
    tracking_number = Column(String(50))
    client = Column(String(50))
    asset_type = Column(String(50))
    linked_with_asset = Column(String(50))
    is_factory_asset = Column(Boolean)
    associated_in_factory = Column(Boolean)
    acquisition_date = Column(DateTime(timezone=True))
    asset_associated_on = Column(DateTime(timezone=True))
    association = Column(String(50))
    associated_by_bd_user_name = Column(String(50))
    associated_by_bd_name = Column(String(50))
    associated_by_app_version = Column(String(50))
    associated_by_app_name = Column(String(50))
    is_missing = Column(Boolean)
    outlet = Column(Text)
    outlet_code = Column(String(50))
    outlet_type = Column(String(50))
    trade_channel = Column(String(50))
    customer_tier = Column(String(50))
    sub_trade_channel = Column(String(50))
    sales_organization = Column(String(50))
    sales_office = Column(String(50))
    sales_group = Column(String(50))
    sales_territory = Column(String(50))
    street = Column(String(100))
    city = Column(String(50))
    state = Column(String(50))
    country = Column(String(50))
    time_zone = Column(String(100))
    latest_health_record_event_time = Column(DateTime(timezone=True))
    battery_level = Column(Integer)
    created_on = Column(DateTime(timezone=True))
    created_by = Column(String(50))
    modified_on = Column(DateTime(timezone=True))
    modified_by = Column(String(50))
    advertisement_url = Column(String(100))
    is_device_registered_in_iot_hub = Column(Boolean)
    is_sd_gateway = Column(Boolean)
    sub_client = Column(String(50))
    device_model_number = Column(String(50))
    module_type = Column(String(50))
    sim_status = Column(String(50))
    last_sim_status_updated_on = Column(DateTime(timezone=True))

    def is_online(self):
        if self.last_ping:
            return datetime.utcnow() - self.last_ping < timedelta(days=30)
        return False


class Movement(Base):
    __tablename__ = "movements"

    id = Column(Integer, primary_key=True)
    movement_type = Column(String(50))
    start_time = Column(DateTime(timezone=True))
    end_time = Column(DateTime(timezone=True))
    duration = Column(Integer)
    latitude = Column(String(50))
    longitude = Column(String(50))
    movement_count = Column(Integer)
    door_open = Column(Boolean)
    displacement_meter = Column(Float)
    accuracy_meter = Column(Float)
    power_status = Column(String(50))
    app_name = Column(String(50))
    app_version = Column(String(50))
    sdk_version = Column(String(50))
    data_uploaded_by = Column(String(50))
    gps_source = Column(String(50))
    event_id = Column(Integer)
    created_on = Column(DateTime(timezone=True))
    gateway_mac = Column(String(50))
    gateway_number = Column(String(50))
    asset_type = Column(String(50))
    month = Column(Integer)
    day = Column(Integer)
    day_of_week = Column(String(50))
    week_of_year = Column(Integer)
    asset_serial_number = Column(String(50))
    technical_id = Column(String(50))
    equipment_number = Column(String(50))
    smart_device_mac = Column(String(50))
    smart_device_number = Column(String(50))
    is_smart = Column(Boolean)
    smart_device_type = Column(String(50))
    outlet = Column(String(100))
    outlet_code = Column(String(50))
    outlet_type = Column(String(50))
    time_zone = Column(String(150))
    client = Column(String(50))
    sub_client = Column(String(50))


class HealthEvent(Base):
    __tablename__ = "health_events"

    id = Column(String(50), primary_key=True)
    event_type = Column(String(50))
    light = Column(Integer)
    light_status = Column(String(50))
    temperature_c = Column(Float)
    evaporator_temperature_c = Column(Float)
    condensor_temperature_c = Column(Float)
    temperature_f = Column(Float)
    evaporator_temperature_f = Column(Float)
    condensor_temperature_f = Column(Float)
    battery = Column(Integer)
    battery_status = Column(String(50))
    interval_min = Column(Integer)
    cooler_voltage_v = Column(Float)
    max_voltage_v = Column(Float)
    min_voltage_v = Column(Float)
    avg_power_consumption_watt = Column(Float)
    total_compressor_on_time_percent = Column(Float)
    max_cabinet_temperature_c = Column(Float)
    min_cabinet_temperature_c = Column(Float)
    ambient_temperature_c = Column(Float)
    max_cabinet_temperature_f = Column(Float)
    min_cabinet_temperature_f = Column(Float)
    ambient_temperature_f = Column(Float)
    app_name = Column(String(50))
    app_version = Column(String(50))
    sdk_version = Column(String(50))
    data_uploaded_by = Column(String(50))
    asset_category = Column(String(50))
    event_id = Column(Integer)
    created_on = Column(DateTime(timezone=True))
    event_time = Column(DateTime(timezone=True))
    gateway_mac = Column(String(50))
    gateway_number = Column(String(50))
    asset_type = Column(String(50))
    month = Column(Integer)
    day = Column(Integer)
    day_of_week = Column(String(50))
    week_of_year = Column(Integer)
    asset_serial_number = Column(String(50))
    technical_id = Column(String(50))
    equipment_number = Column(String(50))
    smart_device_mac = Column(String(50))
    smart_device_number = Column(String(50))
    is_smart = Column(Boolean)
    smart_device_type = Column(String(50))
    outlet = Column(String(100))
    outlet_code = Column(String(50))
    outlet_type = Column(String(50))
    time_zone = Column(String(150))
    client = Column(String(50))
    sub_client = Column(String(50))


class DoorEvent(Base):
    __tablename__ = "door"

    id = Column(String(50), primary_key=True)
    open_event_time = Column(DateTime(timezone=True))
    close_event_time = Column(DateTime(timezone=True))
    event_type = Column(String(50))
    door_open_duration_sec = Column(Integer)
    time_of_day = Column(String(50))
    weekday_weekend = Column(String(50))
    hour_in_day = Column(Integer)
    door_count = Column(Integer)
    additional_info = Column(String(100))
    outlet_territory = Column(String(50))
    door = Column(String(50))
    capacity_type = Column(String(50))
    door_open_target = Column(Integer)
    door_open_temperature = Column(Float)
    door_close_temperature = Column(Float)
    app_name = Column(String(50))
    app_version = Column(String(50))
    sdk_version = Column(String(50))
    data_uploaded_by = Column(String(50))
    asset_category = Column(String(50))
    event_id = Column(Integer)
    created_on = Column(DateTime(timezone=True))
    gateway_mac = Column(String(50))
    gateway_number = Column(String(50))
    asset_type = Column(String(50))
    month = Column(Integer)
    day = Column(Integer)
    day_of_week = Column(String(50))
    week_of_year = Column(Integer)
    asset_serial_number = Column(String(50))
    technical_id = Column(String(50))
    equipment_number = Column(String(50))
    smart_device_mac = Column(String(50))
    smart_device_number = Column(String(50))
    is_smart = Column(Boolean)
    smart_device_type = Column(String(50))
    outlet = Column(String(100))
    outlet_code = Column(String(50))
    outlet_type = Column(String(50))
    time_zone = Column(String(150))
    client = Column(String(50))
    sub_client = Column(String(50))


class AssetsInventory(Base):
    __tablename__ = "assets_inventory"

    id = Column(Integer, primary_key=True, autoincrement=True)

    serial_number = Column(String(100), nullable=False)
    asset_type = Column(String(50))
    material = Column(String(50))
    outlet_name = Column(String(150))

    last_latitude = Column(Float)
    last_longitude = Column(Float)

    is_deleted = Column(Boolean, default=False)

    last_visit_distance_m = Column(Float)

    notes = Column(Text)

    street = Column(String(150))
    city = Column(String(100))

    created_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(ZoneInfo("America/Sao_Paulo")),
    )
    created_by_user = Column(String(100))


class AssetInventoryVisit(Base):
    __tablename__ = "asset_inventory_visits"

    id = Column(Integer, primary_key=True, autoincrement=True)
    asset_id = Column(
        Integer, ForeignKey("assets_inventory.id", ondelete="CASCADE"), nullable=False
    )
    visit_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(ZoneInfo("America/Sao_Paulo")),
    )
    latitude = Column(Float, nullable=False)
    longitude = Column(Float, nullable=False)

    prev_visit_at = Column(DateTime(timezone=True))
    prev_latitude = Column(Float)
    prev_longitude = Column(Float)

    distance_from_prev_m = Column(Float)
    scanned_by = Column(String(150))
    notes = Column(Text)
    created_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(ZoneInfo("America/Sao_Paulo")),
    )


class Alert(Base):
    __tablename__ = "alerts"

    id = Column(String(50), primary_key=True)
    alert_type = Column(String(50))
    alert_text = Column(String(255))
    alert_definition = Column(String(255))
    status = Column(String(50))
    visit_check = Column(String(50))
    asset_serial_number = Column(String(50))
    smart_device_serial_number = Column(String(50))
    asset_equipment_number = Column(String(50))
    asset_technical_identification_number = Column(String(50))
    asset_type = Column(String(50))
    street = Column(String(100))
    street_2 = Column(String(100))
    street_3 = Column(String(100))
    is_smart = Column(Boolean)
    alert_at = Column(DateTime(timezone=True))
    status_changed_on = Column(DateTime(timezone=True))
    priority = Column(String(50))
    age = Column(String(50))
    alert_age_in_minutes = Column(Integer)
    value = Column(String(50))
    last_update = Column(DateTime(timezone=True))
    outlet = Column(String(100))
    outlet_code = Column(String(50))
    outlet_type = Column(String(50))
    outlet_city = Column(String(50))
    client = Column(String(50))
    time_zone = Column(String(150))
    month = Column(Integer)
    day = Column(Integer)
    day_of_week = Column(String(50))
    week_of_year = Column(Integer)
    market = Column(String(50))
    trade_channel = Column(String(50))
    customer_tier = Column(String(50))
    sales_organization = Column(String(50))
    sales_office = Column(String(50))
    sales_group = Column(String(50))
    sales_territory = Column(String(50))
    sales_rep = Column(String(50))
    is_system_alert = Column(Boolean)
    acknowledge_comment = Column(String(255))
    created_on = Column(DateTime(timezone=True))


class Client(Base):
    __tablename__ = "clients"

    id = Column(String(50))
    client_code = Column(String(50), primary_key=True)
    client_name = Column(String(100))
    relevant_business_stream = Column(Text)
    status = Column(String(50))
    contact = Column(String(100))
    subdomain = Column(String(100))
    is_feedback_enabled = Column(Boolean)
    time_zone = Column(String(100))
    vision_image_interval_hours = Column(Float)
    vision_image_interval_door_open = Column(Integer)
    out_of_stock_sku = Column(Integer)
    power_off_duration = Column(Integer)
    temperature_min = Column(Float)
    temperature_max = Column(Float)
    light_min = Column(Integer)
    light_max = Column(Integer)
    door_count = Column(Integer)
    health_intervals_hours = Column(Integer)
    cooler_tracking_threshold_days = Column(Integer)
    cooler_tracking_displacement_threshold_mtr = Column(Float)
    geolocation_api_key = Column(String(500))
    created_on = Column(DateTime(timezone=True))
    created_by = Column(String(100))
    modified_on = Column(DateTime(timezone=True))
    modified_by = Column(String(100))
    fallen_magnet_threshold = Column(Integer)
    vh_enabled = Column(Boolean)
    country = Column(Text)
    shipped_country = Column(Text)
    manual_processing_mode = Column(Boolean)
    is_visit_from_ping = Column(Boolean)
    distance_in_meter = Column(Integer)
    threshold_in_minutes = Column(Integer)
    limit_location_distance = Column(Boolean)
    survey_distance = Column(Integer)
    scene_mode = Column(String(50))
    currency = Column(String(100))
    enable_pic_to_pog = Column(Boolean)
    role = Column(String(50))
    default_recognition_mode = Column(String(50))
    disable_geo_data_collection = Column(Boolean)


class VisionAccount(Base):
    __tablename__ = "vision_accounts"

    id = Column(String(50), primary_key=True)
    client_id = Column(String(50))
    username = Column(String(100))
    password = Column(String(255))
    created_on = Column(DateTime(timezone=True))
    created_by = Column(String(100))
    should_import = Column(
        Boolean,
        default=True,
        nullable=False,
        comment="Se deve importar dados deste cliente",
    )


class SubClient(Base):
    __tablename__ = "subclients"

    id = Column(Text)
    subclient_name = Column(String(255))
    subclient_code = Column(String(100), primary_key=True)
    scene_mode = Column(String(50))
    client = Column(String(50))


class AlertsDefinition(Base):
    __tablename__ = "alerts_definition"
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(100))
    type = Column(String(100))
    asset_serial_number = Column(String(100))
    priority = Column(String(50))
    is_active = Column(String(10))
    open_alert = Column(Integer)
    updated_alert = Column(Integer)
    movement_detected = Column(Integer)
    power_off_duration = Column(Integer)
    temperature_below = Column(Integer)
    temperature_above = Column(Integer)
    offline_alert_time = Column(Integer)
    online_alert_time = Column(Integer)
    missing_faulty_time = Column(Integer)
    cooler_disconnect_threshold = Column(Integer)
    alert_age_threshold = Column(Integer)
    prolonged_irregularity_min = Column(Integer)
    no_data_threshold = Column(Integer)
    battery_open_threshold = Column(Integer)
    battery_close_threshold = Column(Integer)
    stock_threshold = Column(Integer)
    purity_threshold = Column(Integer)
    planogram_threshold = Column(Integer)
    gps_displacement_threshold = Column(Integer)
    motion_available_time = Column(Integer)
    par_displacement_meter = Column(Integer)
    colas_threshold = Column(Integer)
    flavours_threshold = Column(Integer)
    colas_flavours = Column(Integer)
    lane_threshold = Column(Integer)
    min_stock = Column(Integer)
    alert_text = Column(Text)
    daily_alert = Column(String(10))
    client = Column(String(200))
    outlet = Column(String(200))
    sales_organization = Column(String(200))
    trade_channel = Column(Text)  # Pode ser muito longo
    city = Column(String(200))
    state = Column(String(200))
    sales_rep = Column(String(200))
    supervisor = Column(String(200))
    solution_type = Column(String(200))
    is_system_alert = Column(String(10))
    created_on = Column(DateTime(timezone=True))
    created_by = Column(String(100))
    modified_on = Column(DateTime(timezone=True))
    modified_by = Column(String(100))


class MovementsFindHub(Base):
    __tablename__ = "movements_find_hub"

    id = Column(BigInteger, primary_key=True)
    client = Column(String)
    smart_device_number = Column(String(255))
    latitude = Column(String(50))
    longitude = Column(String(50))
    accuracy_meter = Column(Float)
    gps_source = Column(String(50))
    start_time = Column(DateTime(timezone=True))
    created_on = Column(DateTime(timezone=True))


class GhostAsset(Base):
    __tablename__ = "ghost_assets"

    id = Column(BigInteger, primary_key=True)
    serial_number = Column(String(100))
    asset_serial_number = Column(String(100))
    equipment_number = Column(String(100))
    mac_address = Column(String(100))
    latitude = Column(Float)
    longitude = Column(Float)
    address = Column(Text)
    city = Column(String(100))
    country = Column(String(100))
    reported_by = Column(String(150))
    reporter_client = Column(String(150))
    reported_on = Column(DateTime(timezone=True))
    is_commissioned = Column(Boolean)
    client_id = Column(Integer)
    manufacturer = Column(String(150))
    created_by = Column(String(50), default="import")
    modified_on = Column(DateTime(timezone=True))
    modified_by = Column(String(50), default="import")
